### ISSUE TITLE
Clients are not being properly removed from the ClientManager.Clients

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#126]
![image](https://user-images.githubusercontent.com/9319945/98556348-dcd22680-229a-11eb-89aa-dac61c1505c7.png)

As you can see as players join and leave sometimes they are not being removed from the ClientManager.Clients list.
Once we scale up this could cause large issues.
The big dips are server restarts.

**Comment by AeonLucid** [comment]
This issue is about the skeld.net server, the memory leaks (that aren't shown here) are caused by not properly disposing the MessageWriters. A few of those were PR'd by you into Impostor which I took care of here https://github.com/Impostor/Impostor/commit/62aa0ff832e033d5c76bd054f88c8a65675faa35.

I will look at a fix for the leaking clients.

**Comment by danbudworthmead** [comment]
> This issue is about the skeld.net server, the memory leaks (that aren't shown here) are caused by not properly disposing the MessageWriters. A few of those were PR'd by you into Impostor which I took care of here [62aa0ff](https://github.com/Impostor/Impostor/commit/62aa0ff832e033d5c76bd054f88c8a65675faa35).
> 
> I will look at a fix for the leaking clients.

We've since fixed those leaks but are still seeing the Client list skyrocket.
A recent figure is 10737 clients 370 connected 362 playing.
