### ISSUE TITLE
[API] Add DoingTasksStartedEvent 

### ISSUE THREAD

**Issue by Mr-VIT** [Impostor/Impostor#153]
OnMeetingEnded is not reliable
- [ ] DoingTasksStartedEvent - when players can move - triggers: after Game Started, after Exile results screen if the game is not over

**Comment by AeonLucid** [comment]
Not reliable how?

**Comment by AlexejheroYTB** [comment]
OnMeetingEnded event is actually called as soon as the game's state changes from discussion to tasks. Since there is no packet sent when players can start moving, in order to add an event like the one you are describing, we would have to create a server-side timer to trigger the event. Also, depending on the map, confirm ejects setting, whether the vote was skipped or not, and possibly even the ejected player's name (though im not too sure about that), the time it takes for players to able to move differs. It would take a **lot** of work to make this work perfectly, and if it's not perfect, it would just be even more unreliable.

**Comment by AlexejheroYTB** [comment]
I recommend closing this due to what I said above.
