### ISSUE TITLE
Video guide on setting up the server

### ISSUE THREAD

**Issue by willmendil** [Impostor/Impostor#169]
Hi, Thanks very much for this software, it has worked great for me. I just had issues in making it work the first time, and I'm sure other people must have had the same issue, so I made a video to show the minimum install of your tool. https://youtu.be/NM5w-399HzM I'm just sharing the link if you want to incorporate it in your docs. Thanks again

**Comment by dimaguy** [comment]
Your video is good and all, but I recommend you learn and explain the concepts(for example NAT) that are required to open the server.
You need to be more explicit that TCP ports just wont cut it (so its either UDP or TCP/UDP *only*) instead of showing as indecisive (that matters because the audience has a chance of not care either about which one to choose).
You dont need to censor private IPs but oh well *shrugs*.
You also do not include a disclaimer that it is a security risk to open ports without knowing about what youre doing (which is networking 101).
There is also a [website](https://impostor.github.io/Impostor/) that generates the regioninfo.dat file just in case the person does not want to run (or for some reason can't run) the patcher.
This video does not work first try (as you have to do troubleshooting) where you could just... cut the video to the part where it works.
Also in your comment section theres a person suggesting ngrok, but it won't work as ngrok is tcp only!
