### ISSUE TITLE
Server scalable.

### ISSUE THREAD

**Issue by darkragna** [Impostor/Impostor#208]
Hello, I am impressed with the project, as there are multiple node configurations in the multiple server, is the Impostor scalable server?

How does it behave with multiple players? I don't have much interest in the game itself but for learning hobbies.

Cheers,
Thank you!

**Comment by dimaguy** [comment]
Ask the owners of skeld.net as they run the only publicly big private impostor server.
Basically impostor will start chugging resources like there is no tomorrow (it is very lightweight on the beginning tho, it could very well run on a potato if it was net5 compatible) as there is no hard limit on runtime usage.
It will give some ocasional error now and then but you probably shouldnt worry.
At 1000 players in a node instances have a chance of just quitting and sending players to other nodes that might or might not crash.
Impostor is very efficient, but since the api interface was added it became a tad bit fragmented in the code base
