### ISSUE TITLE
Plugin Event Prevent Default

### ISSUE THREAD

**Issue by xtcp** [Impostor/Impostor#257]
Hello,
Is there any way to prevent the default action of an event using a plugin? E.g.: Listening to the MurderPlayer event and prevent the action from being executed.

Thank you in advance,
Best Regards

**Comment by kantesilvestrs** [comment]
This actually is great idea for several events, e.g. on `IPlayerChatEvent` when certain prefix used => prevent message from being propagated to other clients to enable hidden server commands...

**Comment by Herysia** [comment]
Shouldn't the API work with a "hook" system instead of an async event system? (or both).
This would allow to have onBefore...(), onAfter...(), and the possibility to block the propagation of the event through the different "hooks", order defined by a priority system.

This design would allow to code everything from a plugin instead of requiring server core modifications.

I'm talking about a system similar to [this](https://github.com/tera-proxy/tera-proxy-game/blob/master/connection/dispatch/index.js) where each game packet trigger an event, which can be hooked by mods in order to be read, modified or blocked. This system also allow creating fake events (aka fake packets)

**Comment by LorenzoPapi** [comment]
Well for example to prevent the player from venting, you should let the player vent and immediately make him go out of the vent, since blocking the call from the client might result in desyncs

**Comment by kantesilvestrs** [comment]
I had an initial idea - but nothing sophisticated - please don't flame 😄 
![image](https://user-images.githubusercontent.com/52054299/103148955-1e406780-475d-11eb-984b-74a32993bf33.png)
