### ISSUE TITLE
Fast color changing bans host for hacking.

### ISSUE THREAD

**Issue by AerGameChannel** [Impostor/Impostor#286]
# Bug Report

## Base Information
- Windows 10
- Impostor-Server_1.2.2-ci.124_win-x64
- Modded 12.9s (Works without mods too)

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

When there are 2 players in lobby and non-host player starts to change colors very fast, host gets banned for "You were banned for hacking. Please stop" This is output from console:

[16:59:39 INF] MWBMQM - Player not Aer (14) has left.
[16:59:39 INF] MWBMQM - Assigned not Aer (16) as new host.
[16:59:39 INF] Client 14 disconnecting, reason: Client sent SetColor with incorrect color

## Reproduction

1. Start a server
2. Create a room
3. Join this room from second client
4. Start changing colors very fast on non-host client
![image](https://user-images.githubusercontent.com/63594377/104126542-d5e09680-5365-11eb-97b2-30398c473d3a.png)

**Comment by AerGameChannel** [comment]
Also the bug works when there are more than 2 players.

**Comment by AerGameChannel** [comment]
Closing this issue because js6pak and Elsensee made a PRs that will probably fix this bug, ty guys.

**Comment by tsufunk2005** [comment]
Nothing in this thread helped. It still bans you. Where is the fix?

**Comment by JohnTranQUT** [comment]
I believe I am having the same thrown issue too. Since my version had been merge with a lot of pulls, chose not to raise an issue (in case other things was causing it).
I've simple disabled the thrown exception @tsufunk2005 in the impostor.server project, recompiled the project and keep moving along.
Hopefully this problem gets fixed. It recent patch/fix did alleviate the issue but didn't resolve it completely for me.
