### ISSUE TITLE
An assembly specified in the application dependencies manifest (Impostor.Server.deps.json) has already been found but with a different file extension

### ISSUE THREAD

**Issue by TheBotlyNoob** [Impostor/Impostor#345]
Not sure if this is me or the server.

**Comment by JohnTranQUT** [comment]
@TheBotlyNoob
Looks like you are unsure if it's you that is missing a step or if the code is the problem.
I haven't had the same issues as you've outlined here.
Like to suggest to join the Teams' Discord server and bring the issue up there. Likely a quick fix.
It seems to be a "Compilation" error. I am sure someone would be able to help you.
Close the issue here to free up space for the others that should higher prevalence.

**Comment by TheBotlyNoob** [comment]
ok.
