### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#410]
# Bug Report

## Base Information
- Operating System - ubuntu
- Impostor Version - latest code built locally
- Among Us Version - 2021.5.10/12

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

![image](https://user-images.githubusercontent.com/9319945/118201968-b743f680-b450-11eb-847f-08c62b262494.png)

**Comment by neico** [comment]
This happens when the handshake is not fully completed, as happens with the current version of the [client app](https://github.com/Impostor/Impostor/blob/master/src/Impostor.Client.App/Program.cs#L26)
it's essentially missing a `writeHandshake.Write(0);` (though that client app code has more issues than just that)
It's something that was added with the airship changes

Though this report doesn't provide much info beyond the error itself and so I'd say it's a issue related to third-party code as it works fine using the retail client.

**Comment by danbudworthmead** [comment]
Yeah. It appears to work fine until thousands of people are joining and
leaving. Then the cracks appear.

**Comment by js6pak** [comment]
Please provide reproduction steps. And no, "just join with 1k clients" is not enough - make an stress test tool if you want to be helpful in anyway.
