### ISSUE TITLE
Possibly broken with AU v2021.11.9s

### ISSUE THREAD

**Issue by andrew-vant** [Impostor/Impostor#440]
## Base Information
- Impostor v1.6.0 on Ubuntu 18.04.5 LTS
- Among Us v2021.11.9s on Windows 10

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms

After the recent AU update, it can no longer host or find games on my Impostor instance. The error is "Reliable packet 1 (size=66) was not ack'd after 7503ms (9 resends)." Repeated attempts occasionally produce "An address incompatible with the requested protocol was used" instead. There is no indication of a connection attempt in the server-side Impostor output. I cannot find a client-side log to check.

I watched tcpdump while attempting to host a game and discovered something strange. No packets arrive on the configured UDP port; instead they arrive on port N+3, where N is whatever port is configured in the client's `regionInfo.json`. Reducing the port in regionInfo.json by 3 causes packets to arrive on the expected port according to tcpdump, but does not change the in-game symptoms.

I can give you the address of my server privately if it will help.

## Reproduction

1. Start an Impostor server
2. Configure its address in `regionInfo.json`
3. (optional): On the server, run `tcpdump udp and host $client_ip` to observe the connection.
3. Start AU, select the private server, and try to host a game.

**Comment by AeonLucid** [comment]
This is because since the latest update, Among Us forces DTLS for all connections. Where as previously it was only used with the auth server. We are aware of this issue.

**Comment by Alexadnar** [comment]
may I ask when will this issue be fixed? or is there any other way to hold a game on private server?

**Comment by gOOvER** [comment]
> may I ask when will this issue be fixed? or is there any other way to hold a game on private server?

you can evrytime do a PR to fix it

**Comment by gOOvER** [comment]
check commits. This project look like dead ;)

**Comment by Alexadnar** [comment]
what a pity...

**Comment by miniduikboot** [comment]
Sorry for not keeping this issue updated. We're hard at work trying to make Impostor compatible with 2021.11.9, but because of the amount of changes in there and the lack of time we have to fix them, we haven't pushed it to the master branch yet.

You can try a build from the [2021.11.9](https://github.com/Impostor/Impostor/commits/2021.11.9) branch, which works fine but with a few caveats:
1. You need a client mod like [Reactor](https://github.com/NuclearPowered/Reactor) to disable DTLS, as well as an [Impostor plugin](https://github.com/NuclearPowered/Reactor.Impostor). If you're playing with mods that are not compatible with Reactor, you can install [my standalone version](https://github.com/miniduikboot/Mini.RegionPortFixer) instead. Some popular mods, like The Other Roles, have also started including the necessary patches for custom server support. Unmodded clients currently cannot be supported without a game patch, which may happen sooner or later.
2. You need to disable Anticheat for now, otherwise people will get kicked if they kill another player.

If you have any other issues, please contact us via [Discord](https://discord.gg/RRWEBnZZQF), as we're faster to reply there.

**Comment by Alexadnar** [comment]
thx for ur hard working~ wish everything goes well~
