### ISSUE TITLE
Cannot connect destination host

### ISSUE THREAD

**Issue by waki285** [Impostor/Impostor#510]
# Bug Report
my config.json file...
![Screenshot 2023-01-24 13 16 32](https://user-images.githubusercontent.com/67305123/214211176-95e8f825-eeea-41af-8527-0db6f39af65b.png)

When I start the Impostor server and try to create a room with Among Us, it initially succeeds and I can create the room successfully.
However, when I leave the room and try to create it again, I get a "Cannot connect to destination host" error.
There does not appear to be an error on the Impostor side.
The local IP of the server is opened on the router side.
(192.168.0.xx:22023 -> 0.0.0.0:22023)

![image](https://user-images.githubusercontent.com/67305123/214212032-06fb4d62-49f3-4cd7-ad13-fd18237dc0bc.png)

How can I get connected again?

## Base Information
- Operating System Ubuntu Server 22.10
- Impostor Version v1.8.0
- Among Us Version v2022.12.14a

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Unable to connect, "Cannot connect to destination host" error occurs on the Among Us side, and you are logged out on the Among Us side (I can log in again).

## Reproduction

1. make room. (At this point, the connection can be made successfully.)
2. leave the room.
3. Try to create a room again.
4. Error occurs.

**Comment by miniduikboot** [comment]
Hi there,

Unfortunately this is an issue with Among Us 12.8 and 12.4 where it requires you to use HTTP Matchmaking. Impostor only supports HTTP Matchmaking using a plugin, Impostor.Http: https://github.com/Impostor/Impostor.http . The Docs are unfortunately lacking but let me summarize the process:

1. Install Impostor.Http according to its installation procedure.
2. Because you want to use Android, you need to enable HTTPS support: we recommend that this is done using a reverse proxy like Nginx or Apache. See the end of this post for an example nginx configuration
3. Create a new regionFile or click the deeplink button again on https://impostor.github.io/Impostor/

If you run into issues, feel free to contact us on Discord, that might be faster than writing replies on GitHub.

Sorry the docs aren't great, I'm working on improving it

---8<---
Example Nginx configuration, for Debian/Ubuntu servers throw this in /etc/nginx/sites.enabled then restart nginx:
```
server {
    listen 443 ssl http2;
    server_name YOUR.HOSTNAME.HERE;

    # Get a free SSL certificate from Let's Encrypt using certbot: https://certbot.eff.org/
    ssl_certificate /etc/letsencrypt/live/YOUR.HOSTNAME.HERE/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/YOUR.HOSTNAME.HERE/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/YOUR.HOSTNAME.HERE/fullchain.pem;

    location / {
        # Put your ListenPort from config_http.json in here, default is 22000
        proxy_pass http://localhost:22000;
        proxy_pass_header Server;
        proxy_buffering off;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_http_version 1.1;  # recommended with keepalive connections
    }

    # SSL Configuration
    # From https://ssl-config.mozilla.org/#server=nginx&version=1.16.1&config=intermediate&openssl=1.1.1d&guideline=5.6
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    ssl_dhparam /path/to/dhparam;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    #add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # replace with the IP address of your resolver
    resolver 127.0.0.1;
    # end of SSL Configuration


}
```

**Comment by waki285** [comment]
Resolved (Use Impostor.Http Plugin)
