### ISSUE TITLE
DISCONNECTED

### ISSUE THREAD

**Issue by TechDevOfficial** [Impostor/Impostor#538]
# Bug Report

## Base Information
- Operating System
- Impostor Version
- Among Us Version

## I confirm:
- [ ] that I have searched for an existing bug report for this issue.

## Symptoms 

Enter Symptoms on this line.

## Reproduction

![image](https://github.com/Impostor/Impostor/assets/89547375/1fc7fe61-430c-40a9-a478-6becc8c644aa)

Enter reproductions steps here.

Hi. I have 2020.12.9 but the game disconnect me

**Comment by TechDevOfficial** [comment]
Impostor 1.2.2
Windows 11

**Comment by miniduikboot** [comment]
Hi there, unfortunately we don't support old versions of Impostor/Among Us, as most players/servers are on the most recent version of Among Us and our time is limited. 

Looking through our release history it looks like we have never made a release that is compatible with that version of Among Us, so I recommend that you look through our commit history and find a commit that supports that version. Our documentation should have instructions on building Impostor, they have not changed since then.
