### ISSUE TITLE
[UBUNTU 22.02] Says DOT NET is not installed when it is installed

### ISSUE THREAD

**Issue by higps** [Impostor/Impostor#568]
# Bug Report

## Base Information
- Ubuntu 22.02
- Latest
- Among Us Version

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

![WindowsTerminal_GZA0UwDi0r](https://github.com/Impostor/Impostor/assets/59850204/a923741a-65a8-4de3-9798-89cc5123f3b6)
![WindowsTerminal_xDJkFyEjQT](https://github.com/Impostor/Impostor/assets/59850204/c1be83ed-6df2-4639-aaab-b24e9cea4332)

## Symptoms 

After installing latest ASP and NETCore and SDK with versions 8.0.1 it still says it needs that version.

I have provided screenshots of the installation terminal. Is there something I've been missing here? I've tried uninstalling and followed the guides on the microsoft pages

**Comment by miniduikboot** [comment]
Hmm, that's strange, I haven't heard of that before. I do usually install the packages though instead of manually installing it through dotnet-install, but this can be saved.

1. Can you try opening a new shell and see if it works then? 
2. If it still doesn't, try running `set -u; echo $DOTNET_ROOT`. If that returns `-bash: DOTNET_ROOT: unbound variable`, define it by adding it to your bashrc: `echo 'export DOTNET_ROOT=/usr/share/dotnet' >> ~/.bashrc`. This shouldn't be necessary though, as the default value of DOTNET_ROOT if unset should be /usr/share/dotnet

Alternatively you should consider using the dotnet packages instead of dotnet-install, as [dotnet-install.sh is intended for use in CI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#purpose). You can find the install instructions for Ubuntu 20.04 on this page: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204

**Comment by higps** [comment]
I ran 
ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
and that seems to have fixed it.
